### ISSUE TITLE
[BUG] Green pieces overlap and pieces exiting the grid

### ISSUE THREAD

**Issue by zyxcyyy** [Fast0n/HamsterKombatMiniGame#1]
![image](https://github.com/user-attachments/assets/d938306d-2d62-4d3f-a6e0-4b1f834e7b48)
![image](https://github.com/user-attachments/assets/6ac56488-ee71-49fb-b405-4723d2f44c48)

**Comment by Fast0n** [comment]
Fixed the overlapping of pieces

**Comment by Fast0n** [comment]
Fixed the site with the new graphical interface

**Comment by Fast0n** [comment]
Corrected the site with the new graphical interface.

**Comment by zyxcyyy** [comment]
![image](https://github.com/user-attachments/assets/9578f07c-257c-47a7-a136-cbfc51e3159c)
